"""criacao inicial

Revision ID: 77b33f04f38a
Revises: 
Create Date: 2026-04-09 13:11:22.789655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b33f04f38a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bairros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor_entrega', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_loja', sa.String(), nullable=True),
    sa.Column('loja_aberta', sa.Boolean(), nullable=True),
    sa.Column('endereco_loja', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('horario_funcionamento', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impressoras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('finalidade', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('porta', sa.Integer(), nullable=True),
    sa.Column('usb_vendor', sa.String(), nullable=True),
    sa.Column('usb_product', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('porcoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'FINALIZADO', 'CANCELADO', name='statuspedido'), nullable=False),
    sa.Column('tipo_pedido', sa.Enum('ENTREGA', 'RETIRADA', 'BALCAO', name='tipopedido'), nullable=False),
    sa.Column('nome_cliente', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('preco_total', sa.Float(), nullable=True),
    sa.Column('valor_entrega', sa.Float(), nullable=True),
    sa.Column('forma_pagamento', sa.Enum('PIX', 'DINHEIRO', 'CARTAO', name='formapagamento'), nullable=True),
    sa.Column('troco_para', sa.Float(), nullable=True),
    sa.Column('impresso_cozinha', sa.Boolean(), nullable=True),
    sa.Column('impresso_motoboy', sa.Boolean(), nullable=True),
    sa.Column('data_impressao_cozinha', sa.DateTime(), nullable=True),
    sa.Column('data_impressao_motoboy', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('bairro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bairro_id'], ['bairros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_codigo'), 'pedidos', ['codigo'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('imagem_url', sa.String(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('porcao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['porcao_id'], ['porcoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('itens_pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('nomedoproduto', sa.String(), nullable=False),
    sa.Column('variacao_nome', sa.String(), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_impressao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_comanda', sa.String(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('impressora_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['impressora_id'], ['impressoras.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variacoes_produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('acrescimo', sa.Float(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variacoes_produto')
    op.drop_table('logs_impressao')
    op.drop_table('itens_pedidos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_pedidos_codigo'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_table('usuarios')
    op.drop_table('porcoes')
    op.drop_table('impressoras')
    op.drop_table('configuracoes')
    op.drop_table('categorias')
    op.drop_table('bairros')
    # ### end Alembic commands ###
